# Generated by Django 5.0.7 on 2024-08-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='competed',
            new_name='completed',
        ),
    ]
