# Generated by Django 5.0.7 on 2024-07-24 09:28

import django.core.files.storage
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productattachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattachment',
            old_name='id_free',
            new_name='is_free',
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='E:\\Django course\\Micro Ecommerse\\ local-cdn\\protected'), upload_to=products.models.handle_product_attachment_upload),
        ),
    ]
